name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      BACKEND_REPO: ${{ secrets.ECR_BACKEND_REPO }}
      FRONTEND_REPO: ${{ secrets.ECR_FRONTEND_REPO }}
      CLUSTER_NAME: resumexpert-cluster
      BACKEND_SERVICE: resumexpert-backend-service
      FRONTEND_SERVICE: resumexpert-frontend-service
      BACKEND_TASK: resumexpert-backend-task
      FRONTEND_TASK: resumexpert-frontend-task
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # ================= BACKEND =================

      - name: Build and push backend image
        run: |
          ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_REPO
          docker build --no-cache -t $ECR_URI:$IMAGE_TAG ./backend
          docker push $ECR_URI:$IMAGE_TAG

      - name: Download backend task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition $BACKEND_TASK \
            --query taskDefinition \
            > backend-task.json

          jq 'del(
            .taskDefinitionArn,
            .revision,
            .status,
            .requiresAttributes,
            .compatibilities,
            .registeredAt,
            .registeredBy,
            .enableFaultInjection
          )' backend-task.json > backend-task-clean.json

      - name: Render backend task definition
        id: render-backend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: backend-task-clean.json
          container-name: backend
          image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_BACKEND_REPO }}:${{ github.sha }}

      - name: Deploy backend to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-backend.outputs.task-definition }}
          service: ${{ env.BACKEND_SERVICE }}
          cluster: ${{ env.CLUSTER_NAME }}
          wait-for-service-stability: true

      # ================= FRONTEND =================

      - name: Build and push frontend image
        run: |
          ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_REPO
          docker build --no-cache -t $ECR_URI:$IMAGE_TAG ./frontend
          docker push $ECR_URI:$IMAGE_TAG

      - name: Download frontend task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition $FRONTEND_TASK \
            --query taskDefinition \
            > frontend-task.json

          jq 'del(
            .taskDefinitionArn,
            .revision,
            .status,
            .requiresAttributes,
            .compatibilities,
            .registeredAt,
            .registeredBy,
            .enableFaultInjection
          )' frontend-task.json > frontend-task-clean.json

      - name: Render frontend task definition
        id: render-frontend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: frontend-task-clean.json
          container-name: frontend
          image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_FRONTEND_REPO }}:${{ github.sha }}

      - name: Deploy frontend to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-frontend.outputs.task-definition }}
          service: ${{ env.FRONTEND_SERVICE }}
          cluster: ${{ env.CLUSTER_NAME }}
          wait-for-service-stability: true
